name: Build and Publish process_list.exe

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install MinGW-w64
      - name: Install MinGW-w64
        run: |
          sudo apt-get update
          sudo apt-get install -y mingw-w64

      # Build the executable with MinGW
      - name: Build process_list.exe
        run: |
          x86_64-w64-mingw32-gcc -o process_list.exe process_list.c -lpsapi
        shell: bash

      # Upload the built executable as an artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: process_list.exe
          path: process_list.exe

      - name: Create Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./process_list.exe
          asset_name: process_list.exe
          asset_content_type: application/octet-stream
